import { Event } from '../models/event.model';

export const events = [
    {
        MeetingID: 2,
        TeamID: 1,
        Title: 'Coffee buyer delivery review',
        Description: '',
        StartTimezone: undefined,
        Start: 1370865600000,
        End: 1370872800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 3,
        TeamID: 2,
        Title: 'Roastery partner warehouse tour',
        Description: '',
        StartTimezone: undefined,
        Start: 1370865600000,
        End: 1370872800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 4,
        TeamID: 1,
        Title: 'Production batch planning',
        Description: '',
        StartTimezone: undefined,
        Start: 1371006000000,
        End: 1371006000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: true
    },
    {
        MeetingID: 5,
        TeamID: 3,
        Title: 'Supplier intake review',
        Description: '',
        StartTimezone: undefined,
        Start: 1371211200000,
        End: 1371222000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 7,
        TeamID: 1,
        Title: 'Receiving shift briefing - Mathew Stevens',
        Description: 'Inbound receiving lead',
        StartTimezone: undefined,
        Start: 1372413600000,
        End: 1372419000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 8,
        TeamID: 4,
        Title: 'Delivery handoff - Mary Smith',
        Description: 'Delivery coordinator',
        StartTimezone: undefined,
        Start: 1372082400000,
        End: 1372087800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 9,
        TeamID: 4,
        Title: 'Inventory count review - John Stewart',
        Description: 'Delivery coordinator',
        StartTimezone: undefined,
        Start: 1372156200000,
        End: 1372161600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 10,
        TeamID: 1,
        Title: 'Roasting line handoff - Laura Bailey',
        Description: 'Dispatch coordination',
        StartTimezone: undefined,
        Start: 1372176000000,
        End: 1372181400000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 11,
        TeamID: 4,
        Title: 'Dispatch shift briefing - Jenny Baxter',
        Description: 'Dispatch coordination',
        StartTimezone: undefined,
        Start: 1372323600000,
        End: 1372329000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 12,
        TeamID: 2,
        Title: 'Receiving dock briefing - Bernard Atkins',
        Description: 'Dispatch coordination',
        StartTimezone: undefined,
        Start: 1372258800000,
        End: 1372264200000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 13,
        TeamID: 4,
        Title: 'Coffee shipment planning',
        Description: '',
        StartTimezone: undefined,
        Start: 1370422800000,
        End: 1370430000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 14,
        TeamID: 1,
        Title: 'Carrier dispatch sync - North hub',
        Description: '',
        StartTimezone: undefined,
        Start: 1372239000000,
        End: 1372242600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 15,
        TeamID: 4,
        Title: 'Carrier dispatch sync - East hub',
        Description: '',
        StartTimezone: undefined,
        Start: 1372257000000,
        End: 1372260600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 16,
        TeamID: 2,
        Title: 'Warehouse safety training',
        Description: '',
        StartTimezone: undefined,
        Start: 1372251600000,
        End: 1372253400000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 17,
        TeamID: 3,
        Title: 'Packaging line review',
        Description: '',
        StartTimezone: undefined,
        Start: 1372165200000,
        End: 1372170600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 18,
        TeamID: 2,
        Title: 'Inventory status review',
        Description: '',
        StartTimezone: undefined,
        Start: 1370365200000,
        End: 1370370600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 19,
        TeamID: 4,
        Title: 'Quality control checks',
        Description: '',
        StartTimezone: undefined,
        Start: 1371114000000,
        End: 1371142800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 20,
        TeamID: 4,
        Title: 'Maintenance shift briefing - Bobby Rooney',
        Description: 'Dispatch coordination',
        StartTimezone: undefined,
        Start: 1370253600000,
        End: 1370259000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 21,
        TeamID: 3,
        Title: 'Weekly warehouse huddle',
        Description: '',
        StartTimezone: undefined,
        Start: 1370530800000,
        End: 1370536200000,
        EndTimezone: undefined,
        RecurrenceRule: 'FREQ=WEEKLY;BYDAY=TH',
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 22,
        TeamID: 3,
        Title: 'Roast line performance review',
        Description: '',
        StartTimezone: undefined,
        Start: 1372428000000,
        End: 1372435200000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 23,
        TeamID: 1,
        Title: 'Supplier coordination call',
        Description: '',
        StartTimezone: undefined,
        Start: 1371812400000,
        End: 1371814200000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 24,
        TeamID: 2,
        Title: 'Production shift briefing - Larry Thompson',
        Description: 'Production shift lead',
        StartTimezone: undefined,
        Start: 1371463200000,
        End: 1371468600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 25,
        TeamID: 4,
        Title: 'Coffee shipment planning',
        Description: '',
        StartTimezone: undefined,
        Start: 1370908800000,
        End: 1370908800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: true
    },
    {
        MeetingID: 26,
        TeamID: 4,
        Title: 'Carrier coordination call',
        Description: '',
        StartTimezone: undefined,
        Start: 1370957400000,
        End: 1370961000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 27,
        TeamID: 2,
        Title: 'Monthly order forecast',
        Description: '',
        StartTimezone: undefined,
        Start: 1371657600000,
        End: 1371663000000,
        EndTimezone: undefined,
        RecurrenceRule: 'FREQ=MONTHLY;BYMONTHDAY=19',
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 28,
        TeamID: 1,
        Title: 'Supplier phone check-in',
        Description: '',
        StartTimezone: undefined,
        Start: 1371461400000,
        End: 1371465000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 29,
        TeamID: 4,
        Title: 'Weekly receiving checklist',
        Description: '',
        StartTimezone: undefined,
        Start: 1370275200000,
        End: 1370278800000,
        EndTimezone: undefined,
        RecurrenceRule: 'FREQ=WEEKLY;BYDAY=MO',
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 30,
        TeamID: 2,
        Title: 'Shift coverage planning',
        Description: '',
        StartTimezone: undefined,
        Start: 1370264400000,
        End: 1370269800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 31,
        TeamID: 3,
        Title: 'Customer delivery call',
        Description: '',
        StartTimezone: undefined,
        Start: 1370354400000,
        End: 1370358000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 32,
        TeamID: 3,
        Title: 'Warehouse support call',
        Description: '',
        StartTimezone: undefined,
        Start: 1370340000000,
        End: 1370343600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 33,
        TeamID: 1,
        Title: 'Warehouse operations sync',
        Description: '',
        StartTimezone: undefined,
        Start: 1370440800000,
        End: 1370444400000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 34,
        TeamID: 4,
        Title: 'Warehouse workflow review',
        Description: '',
        StartTimezone: undefined,
        Start: 1370442600000,
        End: 1370449800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 35,
        TeamID: 2,
        Title: 'Inventory system maintenance',
        Description: '',
        StartTimezone: undefined,
        Start: 1370451600000,
        End: 1370455200000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 36,
        TeamID: 1,
        Title: 'Equipment safety inspection',
        Description: '',
        StartTimezone: undefined,
        Start: 1370476800000,
        End: 1370476800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: true
    },
    {
        MeetingID: 37,
        TeamID: 2,
        Title: 'Equipment safety inspection',
        Description: '',
        StartTimezone: undefined,
        Start: 1370476800000,
        End: 1370476800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: true
    },
    {
        MeetingID: 38,
        TeamID: 4,
        Title: 'Equipment inspection follow-up',
        Description: '',
        StartTimezone: undefined,
        Start: 1371686400000,
        End: 1371686400000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: true
    },
    {
        MeetingID: 39,
        TeamID: 4,
        Title: 'Coffee buyer delivery review',
        Description: '',
        StartTimezone: undefined,
        Start: 1591790400000,
        End: 1591797600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 40,
        TeamID: 4,
        Title: 'Roastery partner warehouse tour',
        Description: '',
        StartTimezone: undefined,
        Start: 1591790400000,
        End: 1591797600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 41,
        TeamID: 1,
        Title: 'Production batch planning',
        Description: '',
        StartTimezone: undefined,
        Start: 1591920000000,
        End: 1591920000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: true
    },
    {
        MeetingID: 42,
        TeamID: 3,
        Title: 'Supplier intake review',
        Description: '',
        StartTimezone: undefined,
        Start: 1592136000000,
        End: 1592146800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 43,
        TeamID: 4,
        Title: 'Receiving shift briefing - Mathew Stevens',
        Description: 'Inbound receiving lead',
        StartTimezone: undefined,
        Start: 1593338400000,
        End: 1593343800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 44,
        TeamID: 1,
        Title: 'Delivery handoff - Mary Smith',
        Description: 'Delivery coordinator',
        StartTimezone: undefined,
        Start: 1593007200000,
        End: 1593012600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 45,
        TeamID: 3,
        Title: 'Inventory count review - John Stewart',
        Description: 'Delivery coordinator',
        StartTimezone: undefined,
        Start: 1593079200000,
        End: 1593086400000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 46,
        TeamID: 1,
        Title: 'Roasting line handoff - Laura Bailey',
        Description: 'Dispatch coordination',
        StartTimezone: undefined,
        Start: 1593100800000,
        End: 1593106200000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 47,
        TeamID: 4,
        Title: 'Dispatch shift briefing - Jenny Baxter',
        Description: 'Dispatch coordination',
        StartTimezone: undefined,
        Start: 1593248400000,
        End: 1593253800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 48,
        TeamID: 2,
        Title: 'Receiving dock briefing - Bernard Atkins',
        Description: 'Dispatch coordination',
        StartTimezone: undefined,
        Start: 1593183600000,
        End: 1593189000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 49,
        TeamID: 4,
        Title: 'Coffee shipment planning',
        Description: '',
        StartTimezone: undefined,
        Start: 1591347600000,
        End: 1591354800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 50,
        TeamID: 1,
        Title: 'Carrier dispatch sync - North hub',
        Description: '',
        StartTimezone: undefined,
        Start: 1593163800000,
        End: 1593167400000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 51,
        TeamID: 4,
        Title: 'Carrier dispatch sync - East hub',
        Description: '',
        StartTimezone: undefined,
        Start: 1593180000000,
        End: 1593185400000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 52,
        TeamID: 4,
        Title: 'Warehouse safety training',
        Description: '',
        StartTimezone: undefined,
        Start: 1593176400000,
        End: 1593178200000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 53,
        TeamID: 1,
        Title: 'Packaging line review',
        Description: '',
        StartTimezone: undefined,
        Start: 1593090000000,
        End: 1593095400000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 54,
        TeamID: 3,
        Title: 'Inventory status review',
        Description: '',
        StartTimezone: undefined,
        Start: 1591290000000,
        End: 1591295400000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 55,
        TeamID: 4,
        Title: 'Quality control checks',
        Description: '',
        StartTimezone: undefined,
        Start: 1592038800000,
        End: 1592067600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 56,
        TeamID: 1,
        Title: 'Maintenance shift briefing - Bobby Rooney',
        Description: 'Dispatch coordination',
        StartTimezone: undefined,
        Start: 1591178400000,
        End: 1591183800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 57,
        TeamID: 2,
        Title: 'Roast line performance review',
        Description: '',
        StartTimezone: undefined,
        Start: 1593352800000,
        End: 1593360000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 58,
        TeamID: 3,
        Title: 'Supplier coordination call',
        Description: '',
        StartTimezone: undefined,
        Start: 1592737200000,
        End: 1592739000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 59,
        TeamID: 2,
        Title: 'Production shift briefing - Larry Thompson',
        Description: 'Production shift lead',
        StartTimezone: undefined,
        Start: 1592388000000,
        End: 1592393400000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 60,
        TeamID: 4,
        Title: 'Coffee shipment planning',
        Description: '',
        StartTimezone: undefined,
        Start: 1591833600000,
        End: 1591833600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: true
    },
    {
        MeetingID: 61,
        TeamID: 3,
        Title: 'Carrier coordination call',
        Description: '',
        StartTimezone: undefined,
        Start: 1591882200000,
        End: 1591885800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 62,
        TeamID: 3,
        Title: 'Supplier phone check-in',
        Description: '',
        StartTimezone: undefined,
        Start: 1592386200000,
        End: 1592389800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 63,
        TeamID: 1,
        Title: 'Shift coverage planning',
        Description: '',
        StartTimezone: undefined,
        Start: 1591189200000,
        End: 1591194600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 64,
        TeamID: 2,
        Title: 'Customer delivery call',
        Description: '',
        StartTimezone: undefined,
        Start: 1591279200000,
        End: 1591282800000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 65,
        TeamID: 4,
        Title: 'Warehouse support call',
        Description: '',
        StartTimezone: undefined,
        Start: 1591264800000,
        End: 1591268400000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 66,
        TeamID: 4,
        Title: 'Warehouse operations sync',
        Description: '',
        StartTimezone: undefined,
        Start: 1591365600000,
        End: 1591369200000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 67,
        TeamID: 3,
        Title: 'Warehouse workflow review',
        Description: '',
        StartTimezone: undefined,
        Start: 1591367400000,
        End: 1591374600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 68,
        TeamID: 2,
        Title: 'Inventory system maintenance',
        Description: '',
        StartTimezone: undefined,
        Start: 1591376400000,
        End: 1591380000000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: false
    },
    {
        MeetingID: 69,
        TeamID: 3,
        Title: 'Equipment safety inspection',
        Description: '',
        StartTimezone: undefined,
        Start: 1591401600000,
        End: 1591401600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: true
    },
    {
        MeetingID: 70,
        TeamID: 4,
        Title: 'Equipment safety inspection',
        Description: '',
        StartTimezone: undefined,
        Start: 1591401600000,
        End: 1591401600000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: true
    },
    {
        MeetingID: 71,
        TeamID: 4,
        Title: 'Equipment inspection follow-up',
        Description: '',
        StartTimezone: undefined,
        Start: 1592611200000,
        End: 1592611200000,
        EndTimezone: undefined,
        RecurrenceRule: undefined,
        RecurrenceID: null,
        RecurrenceException: null,
        IsAllDay: true
    }
];

export const sampleData: Event[] = events.map((event) => ({
    id: event.MeetingID,
    title: event.Title,
    start: new Date(event.Start),
    end: new Date(event.End),
    startTimezone: event.StartTimezone,
    endTimezone: event.EndTimezone,
    isAllDay: event.IsAllDay,
    description: event.Description,
    recurrenceRule: event.RecurrenceRule,
    recurrenceId: event.RecurrenceID,
    recurrenceException: event.RecurrenceException,
    teamID: event.TeamID
}));
