name: 💡 Feature request
description: Suggest an idea for this project. As an alternative, please use our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui).
labels: ["Enhancement"]
body:
- type: textarea
  attributes:
    label: Description
    description: Add a concise description of the request and any relevant information.
  validations:
    required: true
