export const accountTransactions = [
    {
      id: 0,
      currency: 'Bitcoin',
      symbol: 'BTC',
      status: 'Receive',
      amount: 0.4558,
      stamp: 'Today, 13:15',
      deduction: null,
    },
    {
      id: 1,
      currency: 'Ethereum',
      symbol: 'ETH',
      status: 'Buy',
      amount: 248.45,
      stamp: 'Today, 8:25',
      deduction: '-420$',
    },
    {
      id: 3,
      currency: 'Monero',
      symbol: 'XMR',
      status: 'Buy',
      amount: 1455.55,
      stamp: 'Yesterday, 22:18',
      deduction: '2396.54$',
    },
    {
      id: 4,
      currency: 'Solana',
      symbol: 'SOL',
      status: 'Receive',
      amount: 1.557,
      stamp: '17 Nov 2021, 14.19',
      deduction: null,
    },
    {
      id: 5,
      currency: 'Cardano',
      symbol: 'ADA',
      status: 'Receive',
      amount: 14.004,
      stamp: '18 Nov 2021, 11.22',
      deduction: null,
    },
    {
      id: 6,
      currency: 'Litecoin',
      symbol: 'LTC',
      status: 'Buy',
      amount: 966.12,
      stamp: '19 Nov 2021, 07.43',
      deduction: '-560$',
    },
    {
      id: 8,
      currency: 'Polkadot',
      symbol: 'DOT',
      status: 'Buy',
      amount: 165.16,
      stamp: '23 Nov 2021, 09.59',
      deduction: '-1260.54$',
    },
    {
      id: 9,
      currency: 'Maker',
      symbol: 'MKR',
      status: 'Buy',
      amount: 366.20,
      stamp: '25 Nov 2021, 13.44',
      deduction: '-953.43$',
    },
  ];
  